package:
    name: sina
    version: 1.5


source:
    git_rev: master
    git_url: https://github.com/LLNL/sina

build:
  number: 0
  noarch: python
  script: python python/setup.py install

 
requirements:
  build:
    - python
    - setuptools
    - six
    - sqlalchemy
  run:
    - python
    - six
    - sqlalchemy
    - enum34  # [ py<34 ]


about:
    home:  https://github.com/LLNL/sina
    summary: A tool for storing Sina-format data to one or more backends (SQL, Cassandra) and querying it using a unified, beginner-friendly Python API.
    license: MIT
    license_file: LICENSE

extra:
  maintainers:
   - HaluskaR



