set(DOXYGEN_EXECUTABLE "doxygen" CACHE PATH "")

set(CMAKE_CXX_COMPILER icc-18.0.1)

string(CONCAT SINA_BASE_CXX_FLAGS "-std=c++11 ")
string(CONCAT SINA_CXX_FLAGS "${SINA_BASE_CXX_FLAGS} -Wall -Werror")
string(CONCAT SINA_CXX_TEST_FLAGS "${SINA_CXX_FLAGS}")

