set(DOXYGEN_EXECUTABLE "doxygen" CACHE PATH "")

set(CMAKE_CXX_COMPILER icc-18.0.1)

string(CONCAT MNODA_BASE_CXX_FLAGS "-std=c++11 ")
string(CONCAT MNODA_CXX_FLAGS "${MNODA_BASE_CXX_FLAGS} -Wall -Werror")
string(CONCAT MNODA_CXX_TEST_FLAGS "${MNODA_CXX_FLAGS}")

